### ISSUE TITLE
Error: npm start

### ISSUE THREAD

**Issue by IxDbloke** [UKHomeOffice/design-system#172]
I get the following error when I run npm start in the Terminal while I'm in the design-system-master folder

> node start.js

fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/Users/admin/Documents/Projects/design-system-master/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/admin/Documents/Projects/design-system-master/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/admin/Documents/Projects/design-system-master/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
gulp exited with code 1

**Comment by zuzak** [comment]
Which version of `node` or `nodejs` are you using?

**Comment by IxDbloke** [comment]
Hi, v12.18.3

**Comment by zuzak** [comment]
This is [apparently](https://github.com/gulpjs/gulp/issues/2324) a known issue with Node v12, which is incompatible with Gulp, the program we use to automate the build and run of the design system.

If you downgrade your version of NodeJS, it should work.

**Comment by karypun** [comment]
For now, you can run these commands when you see the error:
nvm install v11
nvm use v11
npm install
